baseURL = "https://im-anone.github.io/najvaei.ir/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
locale = "fa-ir"
defaultContentLanguage = "fa"
rssLimit = 10
theme = "hugo-texify3"
title = "Najvei.ir"

[languages.fa]
  direction = "rtl"
  title = "Najvaei.ir"
  weight = 1

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"

[markup.goldmark.renderer]
unsafe = true

[params]
title = "Najvaei.ir"
author = "Nima Najvaei"
description = "توضیح سایت شما"
dateFormat = "January 2 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true
customCSS = ["css/rtl.css"]
customJS = []
footnote = """
با استفاده از <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> |
 قالب <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="Im-Anone/najvaei.ir"
        data-repo-id="R_kgDOTCO3KQ"
        data-category="Comments"
        data-category-id="DIC_kwDOTCO3Kc4C_sUE"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="gruvbox"
        data-lang="fa"
        crossorigin="anonymous"
        async>
</script>
"""
[params.buymeacoffee]
code = """
...
"""
